### ISSUE TITLE
Temp files

### ISSUE THREAD

**Issue by SugrivaMonkey** [byronbytes/TasksLegacy#1]
The temp files, I try to clean but it doesn't work, other then that it is amazing

**Comment by byronbytes** [comment]
You did not use the right bug format, but thank you for the feedback!

**Comment by byronbytes** [comment]
I figured out the issue and it will be fixed in the next update!

**Comment by byronbytes** [comment]
We have not found a fix to the problem yet, but we have fixed a similar problem having to do with it.

**Comment by Anu6is** [comment]
Run as Administrator should resolve the access issue.

**Comment by byronbytes** [comment]
The issue has been mostly fixed, but going into my temp folder there are still a lot of untouched files, I will try investigating further, but for now I will close this issue as it is fixed.
