### ISSUE TITLE
Buttons do nothing when clicked

### ISSUE THREAD

**Issue by ghost** [byronbytes/TasksLegacy#2]
**Describe the bug**
No startup services, changelogs and improved task manager, also remove bloat doesn't work, found a bug button works but github doesn't work. Other than that, the cleanup seems to work "fine" though.

**To Reproduce**
1. Click on the buttons mentioned above.

**Expected behavior**
Clicking on them will execute the functions, as the button name specified.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OS Version e.g. 21H1 (Find it by running winver)
- App Version v0.1 Prerelease # 1

**Additional information**
nope ;_;

**Comment by byronbytes** [comment]
I see...

1. We have not currently worked on startup services, improved task manager, or remove bloat yet. 
2. I don't know what you mean by GitHub doesn't work.

With more details this will be investigated further.

**Comment by ghost** [comment]
![Capture](https://user-images.githubusercontent.com/67998246/126899475-bb48b412-eea0-4e35-a7d7-7c74f0df32a8.PNG)

**Comment by byronbytes** [comment]
Oh, I see, I will fix that right now!

**Comment by byronbytes** [comment]
Everything should now have a function by now, so I will mark this closed.
